<?php
declare(strict_types=1);

namespace Mnemesong\CollectionGenerator\hidden\collection;

use Mnemesong\CollectionGenerator\exceptions\SortException;
use Mnemesong\CollectionGenerator\hidden\ObjectObject;
use Webmozart\Assert\Assert;

/**
 * Collection of ObjectObjects.
 *
 * Generated by: mnemesong\collection-generator v.0.1
 */
class ObjectObjectCollection implements \Countable, \JsonSerializable
{
    /* @var \Mnemesong\CollectionGenerator\hidden\ObjectObject[] $objects */
    /* @phpstan-ignore-next-line  */
    protected array $objects = [];

    /**
     * @param ObjectObject[] $objects
     */
    public function __construct(array $objects = [])
    {
        foreach ($objects as $object) {
            $this->add($object);
        }
    }

    /**
     * @param \Mnemesong\CollectionGenerator\hidden\ObjectObject $object
     * @return void
     */
    public function add(ObjectObject $object): void
    {
        $this->objects[] = $object;
    }

    /**
     * @param \Mnemesong\CollectionGenerator\hidden\ObjectObject $object
     * @return int|null
     */
    protected function getIndex(ObjectObject $object): ?int
    {
        $filtered = array_filter($this->objects, function (ObjectObject $innerObject) use ($object) {
            return $innerObject == $object;
        });
        if(count($filtered) > 0) {
            return current(array_keys($filtered));
        }
        return null;
    }

    /**
     * @param \Mnemesong\CollectionGenerator\hidden\ObjectObject $object
     * @return int[]
     */
    protected function getAllIndexes(ObjectObject $object): array
    {
        $filtered = array_filter($this->objects, function (ObjectObject $innerObject) use ($object) {
            return $innerObject == $object;
        });
        return array_keys($filtered);
    }

    /**
     * @return ObjectObject[]
     */
    public function getAll(): array
    {
        return $this->objects;
    }

    /**
     * @param \Mnemesong\CollectionGenerator\hidden\ObjectObject $object
     * @return void
     * @throws \ErrorException
     */
    public function removeObject(ObjectObject $object): void
    {
        $index = $this->getIndex($object);
        if(!isset($index)) {
            throw new \ErrorException('Not found element in collection ' . static::class);
        }
        unset($this->objects[$index]);
        $this->objects = array_values($this->objects);
    }

    /**
     * @param \Mnemesong\CollectionGenerator\hidden\ObjectObject $object
     * @return int
     * @throws \ErrorException
     */
    public function removeAll(ObjectObject $object): int
    {
        $result = 0;
        while($this->getIndex($object) !== null)
        {
            $this->removeObject($object);
            $result++;
        }
        return $result;
    }

    /**
     * @param callable $callbackFunction
     * @return self
     */
    public function filter(callable $callbackFunction): self
    {
        $newArray = array_values(array_filter($this->objects, $callbackFunction));
        return new self($newArray);
    }

    /**
     * @param callable $callbackFunction
     * @return int[]
     */
    public function searchIndexesOf(callable $callbackFunction): array
    {
        $newArray = array_filter($this->objects, $callbackFunction);
        return array_keys($newArray);
    }

    /**
     * @param callable $callbackFunction
     * @return array
     */
    /* @phpstan-ignore-next-line  */
    public function map(callable $callbackFunction): array
    {
        return array_map($callbackFunction, $this->objects);
    }

    /**
     * @param callable $callbackFunction
     * @return void
     * @throws \ErrorException
     */
    public function apply(callable $callbackFunction): void
    {
        $newArray = array_map($callbackFunction, $this->objects);
        $checkFilter = array_filter($newArray, function ($item) {
            return !is_a($item, ObjectObject::class);
        });
        if(!empty($checkFilter)) {
            throw new \ErrorException('Wrong type result at Apply() method execution in collection ' . static::class);
        }
        $this->objects = $newArray;
    }

    /**
     * @return int
     */
    public function count(): int
    {
        return count($this->objects);
    }

    /**
     * @param int $index
     * @return \Mnemesong\CollectionGenerator\hidden\ObjectObject|null
     */
    public function getByIndex(int $index): ?ObjectObject
    {
        if(!isset($this->objects[$index])) {
            return null;
        }
        return $this->objects[$index];
    }

    /**
     * @param int $index
     * @return int|null
     */
    public function getNextIndex(int $index): ?int
    {
        $index++;
        if(isset($this->objects[$index])) {
            return $index;
        }
        return null;
    }

    /**
     * @return int
     */
    public function getFirstIndex(): ?int
    {
        $index = array_key_first($this->objects);
        if(is_null($index)) {
            return null;
        }
        Assert::integer($index);
        return $index;
    }

    /**
     * @return \Mnemesong\CollectionGenerator\hidden\ObjectObject[]
     */
    public function jsonSerialize(): array
    {
        return $this->objects;
    }

    /**
     * @return \Mnemesong\CollectionGenerator\hidden\ObjectObject
     */
    public function getFirst(): ObjectObject
    {
        if($this->count() === 0) {
            throw new \RuntimeException('Error: try to get first element from empty ObjectObjects collection');
        }
        return $this->objects[array_key_first($this->objects)];
    }

    /**
     * @return \Mnemesong\CollectionGenerator\hidden\ObjectObject
     */
    public function getLast(): ObjectObject
    {
        if($this->count() === 0) {
            throw new \RuntimeException('Error: try to get last element from empty ObjectObjects collection');
        }
        return $this->objects[array_key_last($this->objects)];
    }

    /**
     * @param callable $func
     * @return self
     */
    public function assertCount(callable $func): self
    {
        if($func($this->count()) !== true) {
            throw new \AssertionError('Count assert error');
        }
        return $this;
    }

    /**
     * @return \Mnemesong\CollectionGenerator\hidden\ObjectObject|null
     */
    public function getFirstOrNull(): ?ObjectObject
    {
        if($this->count() > 0) {
            return $this->getFirst();
        }
        return null;
    }

    /**
     * @return \Mnemesong\CollectionGenerator\hidden\ObjectObject|null
     */
    public function getLastOrNull(): ?ObjectObject
    {
        if($this->count() > 0) {
            return $this->getLast();
        }
        return null;
    }

    /**
     * @param callable $sortFunc
     * @return $this
     */
    public function sort(callable $sortFunc): self
    {
        if(uasort($this->objects, $sortFunc) === false) {
            throw new SortException('Error while resorting collection');
        }
        $this->objects = array_values($this->objects);
        return $this;
    }

    /**
     * @param int $index
     * @param \Mnemesong\CollectionGenerator\hidden\ObjectObject $newItem
     * @return $this
     */
    public function replaceItemByIndex(int $index, ObjectObject $newItem): self
    {
        if(empty($this->objects[$index])) {
            throw new \RuntimeException('Element for replacing had not found');
        }
        $this->objects[$index] = $newItem;
        return $this;
    }
}